In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

**Preprocessing and basic data analysis**

In [27]:
# Load the kmer data generated by k_mers.py file
meta = pd.read_csv("Data/k(4)mer_data.csv").drop("Unnamed: 0", axis=1) 
meta2 = pd.read_csv("Data/k(3)mer_data.csv").drop("Unnamed: 0", axis=1)

In [28]:
meta2.columns
# earquet

Index(['AAA', 'AAT', 'AAC', 'AAG', 'ATA', 'ATT', 'ATC', 'ATG', 'ACA', 'ACT',
       'ACC', 'ACG', 'AGA', 'AGT', 'AGC', 'AGG', 'TAA', 'TAT', 'TAC', 'TAG',
       'TTA', 'TTT', 'TTC', 'TTG', 'TCA', 'TCT', 'TCC', 'TCG', 'TGA', 'TGT',
       'TGC', 'TGG', 'CAA', 'CAT', 'CAC', 'CAG', 'CTA', 'CTT', 'CTC', 'CTG',
       'CCA', 'CCT', 'CCC', 'CCG', 'CGA', 'CGT', 'CGC', 'CGG', 'GAA', 'GAT',
       'GAC', 'GAG', 'GTA', 'GTT', 'GTC', 'GTG', 'GCA', 'GCT', 'GCC', 'GCG',
       'GGA', 'GGT', 'GGC', 'GGG'],
      dtype='object')

In [29]:
y = pd.read_csv("Data/Taxonomic_data.csv", usecols=['Species'])

In [30]:
x = pd.read_csv("Data/k(7)mer_data.csv").drop("Unnamed: 0", axis=1) 
# x = pd.concat([x, meta, meta2], axis=1)

In [31]:
x.columns

Index(['AAAAAAA', 'AAAAAAT', 'AAAAAAC', 'AAAAAAG', 'AAAAATA', 'AAAAATT',
       'AAAAATC', 'AAAAATG', 'AAAAACA', 'AAAAACT',
       ...
       'GGGGGTC', 'GGGGGTG', 'GGGGGCA', 'GGGGGCT', 'GGGGGCC', 'GGGGGCG',
       'GGGGGGA', 'GGGGGGT', 'GGGGGGC', 'GGGGGGG'],
      dtype='object', length=16384)

In [32]:
train_x, test_x,  train_y, test_y = train_test_split(x,y, test_size=0.33, random_state=7)

In [33]:
train_x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8878 entries, 4934 to 12463
Columns: 16384 entries, AAAAAAA to GGGGGGG
dtypes: float64(16384)
memory usage: 1.1 GB

In [34]:
# min_max_scaler = preprocessing.MinMaxScaler()
# train_x_ = pd.DataFrame(train_x)
# train_x = min_max_scaler.fit_transform(train_x)
# train_x = pd.DataFrame(train_x, columns = train_x_.columns)
train_x.describe()

,AAAAAAA,AAAAAAT,AAAAAAC,AAAAAAG,AAAAATA,AAAAATT,AAAAATC,AAAAATG,AAAAACA,AAAAACT,...,GGGGGTC,GGGGGTG,GGGGGCA,GGGGGCT,GGGGGCC,GGGGGCG,GGGGGGA,GGGGGGT,GGGGGGC,GGGGGGG
count,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,...,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000
mean,0.012278,0.014080,0.016896,0.010588,0.017346,0.005970,0.007096,0.011151,0.006646,0.019712,...,0.029849,0.074341,0.164677,0.097544,0.773260,0.082564,0.126605,0.290831,0.058684,0.039311
std,0.131568,0.133091,0.134030,0.103452,0.138925,0.094148,0.086587,0.105015,0.085312,0.139015,...,0.172155,0.267443,0.397871,0.316197,0.451123,0.313505,0.366087,0.462284,0.254380,0.221438
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,4.000000,3.000000,2.000000,2.000000,4.000000,3.000000,2.000000,1.000000,2.000000,1.000000,...,2.000000,2.000000,4.000000,2.000000,3.000000,4.000000,4.000000,3.000000,4.000000,4.000000

In [35]:
train_x

,AAAAAAA,AAAAAAT,AAAAAAC,AAAAAAG,AAAAATA,AAAAATT,AAAAATC,AAAAATG,AAAAACA,AAAAACT,...,GGGGGTC,GGGGGTG,GGGGGCA,GGGGGCT,GGGGGCC,GGGGGCG,GGGGGGA,GGGGGGT,GGGGGGC,GGGGGGG
4934,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1943,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10043,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10180,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
968,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5699,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10742,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
9412,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
12463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
gnb = GaussianNB()
y_pred = gnb.fit(train_x, train_y).predict(test_x)
# clf.score(test_x, test_y)

c:\Users\anant\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [40]:
print("Number of mislabeled points out of a total %d points : %d"    % (test_x.shape[0], (test_y.Species != y_pred).sum()))

Number of mislabeled points out of a total 4374 points : 955

In [42]:
print("accuracy:", 100-1021/4374*100)

accuracy: 76.65752171925011

In [43]:

from sklearn.model_selection import cross_val_score
gsv = GaussianNB()
scores = cross_val_score(gsv, x, y, cv=5)

c:\Users\anant\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
c:\Users\anant\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\anant\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\anant\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\anant\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\anant\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [44]:
scores

array([0.80309317, 0.80460204, 0.79698113, 0.79018868, 0.78150943])

In [45]:
scores.mean()

0.795274890927596

In [46]:
from sklearn import metrics

f1 = metrics.f1_score(test_y, y_pred, average='weighted')

In [47]:
f1

0.7637193345784854

In [48]:
78.14

78.14